---
- name: Collect host entry
  ansible.builtin.set_fact:
    host_entry: "{{ host_entry + item }}"

- name: Add IP address of all hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].system_role }}"
    state: present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_inventory_hostnames: "{{ play_hosts }}"
