---
- name: Check for ssh_config file
  ansible.builtin.stat:
    path: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/config') }}"
  register: ssh_config_check
  tags: ssh_config

- name: Forward ssh agent
  community.general.ssh_config:
    user: ansible
    forward_agent: true
    host: '*'
    state: present
  when: not ssh_config_check.stat.exists
  tags: ssh_config
