---
- name: Add managed node
  hosts: '{{ node }}'
  gather_facts: no
  serial: 1
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_become_method: sudo
  roles:
    - add_managed_node
    - add_known_hosts

- name: Enable ssh agent forwarding for ansible user
  hosts: localhost
  gather_facts: no
  become: no
  roles:
    - configure_ssh_client
  tags: ssh_config