---
# grabs the expired cons3rt created password and changes it to:
# --extra-vars "new_password=foopassword"
# you will also need:
# --extra-vars "node=foonode"
- name: Change expired password
  hosts: '{{ node }}'
  gather_facts: no
  serial: 1
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_become_method: sudo
  roles:
    - change_expired_password
