---
# grabs the expired cons3rt created password and changes it to:
# --extra-vars "new_password=foopassword"
# you will also need:
# --extra-vars "node=foonode"
- name: Change password
  hosts: '{{ node }}'
  gather_facts: no
  serial: 1
  roles:
    - change_password
